name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Format
              uses: cargo fmt --all -- --check

            - name: Cargo cache
              uses: actions/cache@v3
              continue-on-error: false
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  ~/.cargo/git/worktrees/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-cargo-

            - name: Clippy
              run: cargo clippy --all-features -- -D warnings

            - name: Test
              run: cargo test
