name: release

on:
    push:
        tags:
            - "*"


permissions:
    contents: write

jobs:
    check-version:
        name: Check version validity
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check tag version
              id: check-tag-version
              run: |
                tag_version=$(printf "%q" ${{ github.ref_name }})
                if ! [[ $tag_version =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+)?$ ]]; then
                  echo "stable=true" >> $GITHUB_OUTPUT
                else
                  echo "stable=false" >> $GITHUB_OUTPUT
                fi
            - name: Check version
              if: steps.check-tag-version.outputs.stable == 'true'
              run: |
                bash .github/scripts/check-tag-version.sh

    publish-linux-release:
        name: Publish release ${{ matrix.arch }}
        runs-on: ubuntu-latest
        needs: check-version
        strategy:
            matrix:
                arch: [x86_64-unknown-linux-gnu]
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                target: ${{ matrix.arch }}
                toolchain: stable
                profile: minimal
                override: true
            - name: Install Cross
              run: cargo install cross --target ${{ matrix.arch }}
            - name: Build for ${{ matrix.arch }}
              run: cross build --target ${{ matrix.arch }} --release
            - name: Publish release
              uses: svenstaro/upload-release-action@2.6.1
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: target/${{ matrix.arch }}/release/qdrant-kafka-ingestor
                asset_name: qdrant-kafka-ingestor-${{ matrix.arch }}
                tag: ${{ github.ref }}


    publish-apple-release:
        name: Publish release for apple-silicon
        runs-on: macos-12
        needs: check-version
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                profile: minimal
                target: aarch64-apple-darwin
                override: true
            - name: Cargo build
              uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release --target aarch64-apple-darwin
            - name: Public release
              uses: svenstaro/upload-release-action@2.6.1
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: target/aarch64-apple-darwin/release/qdrant-kafka-ingestor
                asset_name: qdrant-kafka-ingestor-apple-silicon
                tag: ${{ github.ref }}
